In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'

In [3]:
!wget $data -O data_HW3.csv

--2023-09-30 10:43:29--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1,4M) [text/plain]
Saving to: 'data_HW3.csv'

     0K .......... .......... .......... .......... ..........  3% 1,39M 1s
    50K .......... .......... .......... .......... ..........  6% 4,60M 1s
   100K .......... .......... .......... .......... .......... 10% 2,48M 1s
   150K .......... .......... .......... .......... .......... 13% 6,65M 0s
   200K .......... .......... .......... .......... .......... 17% 6,17M 0s
   250K .......... .......... .......... .......... .......... 20% 6,71M 0s
   300K .......... .......... .......... .......... .......... 24% 1,80M 0s
   350

In [4]:
df = pd.read_csv('data_HW3.csv')
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [5]:
df.nunique()

Make                   48
Model                 915
Year                   28
Engine Fuel Type       10
Engine HP             356
Engine Cylinders        9
Transmission Type       5
Driven_Wheels           4
Number of Doors         3
Market Category        71
Vehicle Size            3
Vehicle Style          16
highway MPG            59
city mpg               69
Popularity             48
MSRP                 6049
dtype: int64

In [6]:
df.columns = df.columns.str.replace(' ', '_').str.lower()

In [7]:
df.head()

make       model  year             engine_fuel_type  engine_hp  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   engine_cylinders transmission_type     driven_wheels  number_of_doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         market_category vehicle_size vehicle_style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway_mpg  city_mpg  popularity   msrp  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [10]:
df.isnull().sum()

make                 0
model                0
year                 0
engine_fuel_type     0
engine_hp            0
engine_cylinders     0
transmission_type    0
driven_wheels        0
number_of_doors      0
market_category      0
vehicle_size         0
vehicle_style        0
highway_mpg          0
city_mpg             0
popularity           0
msrp                 0
dtype: int64

In [9]:
df = df.fillna(0)

In [11]:
df.isnull().sum()

make                 0
model                0
year                 0
engine_fuel_type     0
engine_hp            0
engine_cylinders     0
transmission_type    0
driven_wheels        0
number_of_doors      0
market_category      0
vehicle_size         0
vehicle_style        0
highway_mpg          0
city_mpg             0
popularity           0
msrp                 0
dtype: int64

In [12]:
df.columns = df.columns.str.replace('msrp', 'price').str.lower()
df

make       model  year                engine_fuel_type  engine_hp  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       engine_cylinders transmission_type      driven_wheels  number_of_doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             market_category vehicle_size  vehicle_style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway_mpg  city_mpg  popularity  price  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [13]:
features = [
        'make', 'model', 'year', 'engine_hp',
        'engine_cylinders', 'transmission_type', 
        'vehicle_size', 'highway_mpg', 'city_mpg'
]

# QUESTION 1

In [14]:
df.transmission_type.value_counts()

AUTOMATIC           8266
MANUAL              2935
AUTOMATED_MANUAL     626
DIRECT_DRIVE          68
UNKNOWN               19
Name: transmission_type, dtype: int64

# QUESTION 2

In [15]:
numerical = ['year', 'engine_hp','engine_cylinders', 'highway_mpg', 'city_mpg']

In [16]:
df[numerical]

year  engine_hp  engine_cylinders  highway_mpg  city_mpg
0      2011      335.0               6.0           26        19
1      2011      300.0               6.0           28        19
2      2011      300.0               6.0           28        20
3      2011      230.0               6.0           28        18
4      2011      230.0               6.0           28        18
...     ...        ...               ...          ...       ...
11909  2012      300.0               6.0           23        16
11910  2012      300.0               6.0           23        16
11911  2012      300.0               6.0           23        16
11912  2013      300.0               6.0           23        16
11913  2006      221.0               6.0           26        17

[11914 rows x 5 columns]

In [24]:
for c in numerical:
    print('---')
    print(c)
    print(df[numerical].corrwith(df[c])) 

---
year
year                1.000000
engine_hp           0.338714
engine_cylinders   -0.040708
highway_mpg         0.258240
city_mpg            0.198171
dtype: float64
---
engine_hp
year                0.338714
engine_hp           1.000000
engine_cylinders    0.774851
highway_mpg        -0.415707
city_mpg           -0.424918
dtype: float64
---
engine_cylinders
year               -0.040708
engine_hp           0.774851
engine_cylinders    1.000000
highway_mpg        -0.614541
city_mpg           -0.587306
dtype: float64
---
highway_mpg
year                0.258240
engine_hp          -0.415707
engine_cylinders   -0.614541
highway_mpg         1.000000
city_mpg            0.886829
dtype: float64
---
city_mpg
year                0.198171
engine_hp          -0.424918
engine_cylinders   -0.587306
highway_mpg         0.886829
city_mpg            1.000000
dtype: float64


# QUESTION 3

In [26]:
df['above_average'] = (df.price >= df.price.mean()).astype(int)
df

make       model  year                engine_fuel_type  engine_hp  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       engine_cylinders transmission_type      driven_wheels  number_of_doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             market_category vehicle_size  vehicle_style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway_mpg  city_mpg  popularity  price  above_average  
0               26        19        3916  46135              1  
1               28        19        3916  40650              1  
2               28        20        3916  36350              0  
3               28        18        3916  29450              0  
4               28        18        3916  34500              0  
...            ...       ...         ...    ...            ...  
11909           23        16         204  46120              1  
11910           23        16         204  56670              1  
11911           23        16         204  50620              1  
11912           23        16         204  50920              1  
11913           26        17          61  28995              0  

[11914 rows x 17 columns]

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42) #split in train e test, imposto seed=1

In [29]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42) #split in train e test, imposto seed=1

In [30]:
len(df_train), len(df_test), len(df_val)

(7148, 2383, 2383)

In [31]:
y_train = df_train.above_average.values
y_val   = df_val.above_average.values
y_test  = df_test.above_average.values

In [32]:
del df_train['above_average']
del df_val['above_average']
del df_test['above_average']

In [33]:
df_train = df_train.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)

In [34]:
from sklearn.metrics import mutual_info_score

In [38]:
def mutual_info_score_avg(series):
    return mutual_info_score(series, y_train)

In [61]:
categorical = ['model', 'year', 'engine_hp',
               'engine_cylinders', 'transmission_type', 
               'vehicle_size', 'highway_mpg', 'city_mpg'
]

In [62]:
mi = df_train[categorical].apply(mutual_info_score_avg) #apply the function to each column
mi = mi.sort_values(ascending=False)
round(mi, 2)

model                0.46
engine_hp            0.36
engine_cylinders     0.12
year                 0.07
city_mpg             0.06
highway_mpg          0.04
vehicle_size         0.04
transmission_type    0.02
dtype: float64

# QUESTION 4

In [63]:
from sklearn.feature_extraction import DictVectorizer

In [64]:
dv = DictVectorizer(sparse=False) # transform a dictionary into a vector

In [65]:
dicts = df_train[categorical].to_dict(orient='records')
dicts[0]

{'model': 'Endeavor',
 'year': 2011,
 'engine_hp': 225.0,
 'engine_cylinders': 6.0,
 'transmission_type': 'AUTOMATIC',
 'vehicle_size': 'Midsize',
 'highway_mpg': 19,
 'city_mpg': 15}

In [66]:
dv.fit(dicts)
dv.get_feature_names_out()

array(['city_mpg', 'engine_cylinders', 'engine_hp', 'highway_mpg',
       'model=1 Series', 'model=100', 'model=124 Spider',
       'model=190-Class', 'model=2', 'model=2 Series', 'model=200',
       'model=200SX', 'model=240', 'model=240SX', 'model=3',
       'model=3 Series', 'model=3 Series Gran Turismo', 'model=300',
       'model=300-Class', 'model=3000GT', 'model=300M', 'model=300ZX',
       'model=323', 'model=350-Class', 'model=350Z', 'model=360',
       'model=370Z', 'model=4 Series', 'model=4 Series Gran Coupe',
       'model=400-Class', 'model=420-Class', 'model=456M',
       'model=458 Italia', 'model=4C', 'model=4Runner', 'model=5',
       'model=5 Series', 'model=5 Series Gran Turismo', 'model=500',
       'model=500-Class', 'model=500L', 'model=500X', 'model=500e',
       'model=550', 'model=560-Class', 'model=57', 'model=570S',
       'model=575M', 'model=599', 'model=6', 'model=6 Series',
       'model=6 Series Gran Coupe', 'model=600-Class', 'model=6000',
       'mode

In [67]:
dv.transform(dicts)

array([[1.500e+01, 6.000e+00, 2.250e+02, ..., 0.000e+00, 1.000e+00,
        2.011e+03],
       [1.700e+01, 6.000e+00, 2.760e+02, ..., 0.000e+00, 1.000e+00,
        2.009e+03],
       [1.200e+01, 1.000e+01, 5.700e+02, ..., 0.000e+00, 0.000e+00,
        2.012e+03],
       ...,
       [1.700e+01, 6.000e+00, 2.600e+02, ..., 0.000e+00, 1.000e+00,
        2.012e+03],
       [1.900e+01, 4.000e+00, 1.360e+02, ..., 0.000e+00, 0.000e+00,
        1.993e+03],
       [1.700e+01, 6.000e+00, 3.650e+02, ..., 1.000e+00, 0.000e+00,
        2.015e+03]])

In [68]:
X_train = dv.fit_transform(dicts)
X_train

array([[1.500e+01, 6.000e+00, 2.250e+02, ..., 0.000e+00, 1.000e+00,
        2.011e+03],
       [1.700e+01, 6.000e+00, 2.760e+02, ..., 0.000e+00, 1.000e+00,
        2.009e+03],
       [1.200e+01, 1.000e+01, 5.700e+02, ..., 0.000e+00, 0.000e+00,
        2.012e+03],
       ...,
       [1.700e+01, 6.000e+00, 2.600e+02, ..., 0.000e+00, 1.000e+00,
        2.012e+03],
       [1.900e+01, 4.000e+00, 1.360e+02, ..., 0.000e+00, 0.000e+00,
        1.993e+03],
       [1.700e+01, 6.000e+00, 3.650e+02, ..., 1.000e+00, 0.000e+00,
        2.015e+03]])

In [69]:
from sklearn.linear_model import LogisticRegression

In [70]:
model = LogisticRegression(solver='liblinear', C=10, max_iter=1000, random_state=42)

In [71]:
model.fit(X_train, y_train)

LogisticRegression(C=10, max_iter=1000, random_state=42, solver='liblinear')

In [72]:
model.coef_[0].round(3)

array([ 2.100e-02, -2.130e-01,  3.700e-02,  5.100e-02,  1.024e+00,
       -6.900e-02, -3.200e-02, -8.000e-03, -2.000e-02,  2.620e-01,
       -2.158e+00, -1.900e-02, -3.000e-03, -2.200e-02, -9.290e-01,
        1.997e+00,  2.401e+00, -1.787e+00, -3.580e-01, -5.580e-01,
       -9.880e-01, -4.310e-01, -4.000e-03, -1.300e-02, -1.041e+00,
        3.930e-01, -9.130e-01,  3.662e+00,  2.307e+00, -3.500e-01,
       -4.900e-02,  1.810e-01,  1.000e-03,  2.657e+00,  6.100e-01,
       -9.600e-02,  2.548e+00,  1.256e+00, -6.200e-02, -1.680e+00,
       -1.050e-01, -2.980e-01, -1.030e-01,  1.090e-01, -2.270e-01,
        4.000e-03,  0.000e+00,  5.400e-02,  1.000e-03, -5.490e-01,
        1.750e+00,  6.600e-01, -2.289e+00, -2.800e-02,  2.000e-03,
        6.000e-03, -4.400e-02,  6.960e-01, -4.200e-02, -4.000e-03,
       -3.200e-02, -6.460e-01, -1.000e-02, -9.340e-01, -1.600e-01,
        2.032e+00,  1.965e+00, -5.100e-02,  7.130e-01,  1.933e+00,
       -3.900e-02, -1.830e-01, -2.750e-01,  2.018e+00, -5.090e

In [73]:
model.intercept_

array([-0.39983017])

In [74]:
model.predict(X_train) #val of churn

array([0, 0, 1, ..., 0, 0, 0])

In [75]:
model.predict_proba(X_train) 

array([[9.72511152e-01, 2.74888479e-02],
       [9.58377199e-01, 4.16228011e-02],
       [3.49239826e-04, 9.99650760e-01],
       ...,
       [9.47206643e-01, 5.27933574e-02],
       [9.98091034e-01, 1.90896620e-03],
       [5.87071285e-01, 4.12928715e-01]])

In [76]:
val_dicts = df_val.to_dict(orient='records')

In [77]:
X_val = dv.transform(val_dicts)

In [78]:
y_pred = model.predict_proba(X_val)[:,1]
y_pred >= 0.5 

array([False,  True, False, ..., False,  True,  True])

In [79]:
decision = (y_pred >= 0.5)
decision

array([False,  True, False, ..., False,  True,  True])

In [81]:
acc = (y_val == decision).mean() #shortcut of what is below
round(acc, 2)

0.94

# QUESTION 5