In [3]:
import pandas as pd
#q1
pd.__version__

'1.5.3'

In [118]:
df = pd.read_csv("C:/Users/bergi/Desktop/LM32/ML_ZOOM/datasets_master_housing.csv")
#q2
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [20]:
#q3
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [21]:
#q4
df.ocean_proximity.nunique()

5

In [22]:
#q5
df.groupby('ocean_proximity').median_house_value.mean()

ocean_proximity
<1H OCEAN     240084.285464
INLAND        124805.392001
ISLAND        380440.000000
NEAR BAY      259212.311790
NEAR OCEAN    249433.977427
Name: median_house_value, dtype: float64

In [24]:
#q6
df.total_bedrooms.mean()

537.8705525375618

In [26]:
df.total_bedrooms.fillna(df.total_bedrooms.mean()).mean()

537.8705525375617

In [106]:
#q7
df_1 = df[['housing_median_age', 'total_rooms', 'total_bedrooms','ocean_proximity']]
df_1.groupby('ocean_proximity').count()

housing_median_age  total_rooms  total_bedrooms
ocean_proximity                                                 
<1H OCEAN                      9136         9136            9034
INLAND                         6551         6551            6496
ISLAND                            5            5               5
NEAR BAY                       2290         2290            2270
NEAR OCEAN                     2658         2658            2628

In [107]:
df_1 = df_1[df.ocean_proximity == 'ISLAND']
df_1

housing_median_age  total_rooms  total_bedrooms ocean_proximity
8314                27.0       1675.0           521.0          ISLAND
8315                52.0       2359.0           591.0          ISLAND
8316                52.0       2127.0           512.0          ISLAND
8317                52.0        996.0           264.0          ISLAND
8318                29.0        716.0           214.0          ISLAND

In [109]:
del df_1['ocean_proximity']

In [122]:
import numpy as np
X = np.array(df_1)
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [123]:
XT = X.T
XT

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [124]:
XTX = X.dot(XT)
XTX

array([[3077795., 4260640., 3830881., 1807248., 1311577.],
       [4260640., 5916866., 5322889., 2508292., 1817026.],
       [3830881., 5322889., 4788977., 2256364., 1634008.],
       [1807248., 2508292., 2256364., 1064416.,  771140.],
       [1311577., 1817026., 1634008.,  771140.,  559293.]])

In [125]:
y = [950, 1300, 800, 1000, 1300]
y

[950, 1300, 800, 1000, 1300]

In [126]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 4.50889141e+08, -2.65092831e+09,  2.66146909e+09,
        -5.26157398e+08,  5.04760603e+08],
       [ 2.60444475e+11, -8.57212683e+10, -2.18771394e+10,
         5.28097320e+11, -9.96480838e+11],
       [-2.81125831e+11,  9.36268739e+10,  2.24292933e+10,
        -5.69400064e+11,  1.07463035e+12],
       [ 1.50907516e+11, -5.52172767e+10, -6.69134384e+09,
         3.02798151e+11, -5.72439948e+11],
       [-2.33928769e+11,  8.73028262e+10,  8.53028316e+09,
        -4.68398445e+11,  8.85843939e+11]])

In [134]:
w = XT.dot(XTX_inv)
w

array([[-0.00292969, -0.0151825 ,  0.00458622,  0.03063965, -0.0020752 ],
       [-0.07421875, -0.00274658,  0.00222397, -0.09912109, -0.06201172],
       [ 0.00195312,  0.00033569, -0.00824165,  0.01489258, -0.00561523]])

In [135]:
w = w.dot(y)
w

array([   9.09042358, -252.03552246,    3.2913208 ])